@accentColor = #2E436E
#@accentFocusColor= if(@accentColor, @accentColor, shade(spin(@accentBaseColor,-8),20%))

@itemBG = #191A1C
@secondaryColor = #26282B

List.selectionInactiveBackground = #253258

ComboBox.buttonBackground = over(@nsControlColor,@background)

AD.errorColor = #DB5C5C
AD.accentColor = #253258

AD.secondaryColor = @secondaryColor
AD.itemBG = @itemBG

AD.thumb = #3F4041
AD.track = #252525

Panel.background = @itemBG

Spinner.buttonStyle = win
