@accentColor=#3574F0

@itemBG = #FFFFFF
@secondaryColor = #F0F4F9

*.selectionBackground = #D4E2FF
*.selectionForeground = #000

List.selectionInactiveBackground = #D4E2FF

AD.errorColor = #89343D
AD.accentColor = #D4E2FF

AD.secondaryColor = @secondaryColor
AD.itemBG = @itemBG

AD.thumb = #B9B9B9
AD.track = #C3C3C3

Panel.background = @itemBG
List.background  = @secondaryColor